# Site settings
title: AI for Mathematics (AI4Math)
email: 
description: "AI for Mathematics (AI4Math)"
baseurl: ""
url: "https://ai4math.github.io"
twitter_username: ai4math
github_username: ai4math

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

# links to homeworks
hw_1_colab: https://cs231n.github.io/assignments/2025/assignment1_colab.zip
hw_2_colab: https://cs231n.github.io/assignments/2025/assignment2_colab.zip
hw_3_colab: https://cs231n.github.io/assignments/2025/assignment3_colab.zip
